DEVICE_PATH := device/oppo/CPH2579

# Override Android Platform Version
PLATFORM_VERSION_OVERRIDE := 15
PLATFORM_VERSION := 15

# Architecture & Page Alignment
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

TARGET_CPU_ABI_LIST_64_BIT := arm64-v8a
TARGET_CPU_ABI_LIST_32_BIT := armeabi-v7a,armeabi
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)

# Bootloader & Platform
TARGET_BOOTLOADER_BOARD_NAME := CPH2579
TARGET_BOARD_PLATFORM := mt6769

# Stock Boot Header Setup (OPPO A38 Android 15)
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 buildvariant=user
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 4096
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x04000000 --tags_offset 0x0E000000 --dtb $(TARGET_PREBUILT_DTB) --header_version $(BOARD_BOOT_HEADER_VERSION) --pagesize $(BOARD_KERNEL_PAGESIZE)

# Partitions Setup
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864

# Vendor Boot & Recovery Flags
BOARD_USES_VENDOR_BOOTIMAGE := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true

# Dynamic Partitions
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_SIZE := 0
BOARD_HAS_LARGE_FILESYSTEM := true

# Fix Symlink Issues (AOSP 11+)
TARGET_COPY_OUT_VENDOR := vendor
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# Resolution & Theme Setup
TW_THEME := portrait_hdpi
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2400
TW_SCREEN_WIDTH := 1080
TW_SCREEN_HEIGHT := 2400
TW_MAX_BRIGHTNESS := 2047
TW_DEFAULT_BRIGHTNESS := 1024

# Graphic / Display (Enable DRM for modern MediaTek)
TARGET_USES_DRM_PP := true
TW_NO_MINUI_CUSTOM_GRAPHICS := false
TW_SUPPORT_DRM := true
TW_GRALLOC_HACKS := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_FRAMERATE := 60
# Screen blanking disabled to prevent black screen issues
# TW_NO_SCREEN_BLANK := true
# TW_SCREEN_BLANK_ON_BOOT := true
# OrangeFox specific settings
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_HIDE_NOTCH := 1
OF_SCREEN_H := 2400
OF_USE_GREEN_LED := 0
OF_FL_PATH1 := /sys/class/flashlight_core/flashlight/flashlight_torch
TW_BATTERY_SYSFS_PATH := /sys/class/power_supply/mtk-battery
# TWRP Specific Flags
RECOVERY_SDCARD_ON_DATA := true
# TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXTRA_LANGUAGES := true
# TW_INCLUDE_CRYPTO := true
# TW_INCLUDE_CRYPTO_FBE := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_INCLUDE_REPACKTOOLS := true

# Build Fixes
DISABLE_VTS := true
ALLOW_MISSING_DEPENDENCIES := true
TW_SKIP_ADDITIONAL_FSTAB := true
TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/libboot_control_client.so
TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.boot-V1-ndk.so
